# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Mediator"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: jg9502@naver.com
#blog logo
logo: "/assets/images/kokodak_logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/kokodak_background.jpg"

name: 'Kim Jeonggi'
author: 'Kim Jeonggi'
author_image: "/assets/images/mypic.jpg"

paginate:	5

url: "http://kokodakdak.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	instagram
    url:	https://www.instagram.com/jin_zenggu/
    desc: My instagram
    share_url:
    share_title:
    share_link:

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/kokodakdak
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
